apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default
spec:
  selector:
    matchLabels:
      run: nginx-default
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-default
    spec:
      containers:
      - name: nginx-default
        image: containerregistry.azurecr.io/nginx:default
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-default
  labels:
    run: nginx-default
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-default
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-first
spec:
  selector:
    matchLabels:
      run: nginx-first
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-first
    spec:
      containers:
      - name: nginx-first
        image: containerregistry.azurecr.io/nginx:first
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-first
  labels:
    run: nginx-first
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-first
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-second
spec:
  selector:
    matchLabels:
      run: nginx-second
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-second
    spec:
      containers:
      - name: nginx-second
        image: containerregistry.azurecr.io/nginx:second
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-second
  labels:
    run: nginx-second
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-second